Rails.application.config.assets.precompile += %w( leaflet/Google.min.js )
Rails.application.config.assets.precompile += %w( leaflet/leaflet.draw.0.2.3dev.min.js )
Rails.application.config.assets.precompile += %w( mapEditor.js )
Rails.application.config.assets.precompile += %w( csv.js )
Rails.application.config.assets.precompile += %w( jquery.csv.js )