# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8940d23d0db3ae4bbd5aa9615747259bc45fded769cf4154c7e0ce074c6d90a07c91639c20edd0f59c29bebd0235e52f9599b6fb4661893d1f7917a8136f6fc7

test:
  secret_key_base: 3b51b2246e59fe495318109fb5cc9c5e3e1a926fc8a4ef75fc2a19be708b5c8226b2ecbb17b643d966852c8046d516327f38497d01a5a7e0fee30fd6693f9826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
